# TODO: not quite right - somehow this fails with py 3.10.6
[project]
name = "shepherd_data"
description = "Programming- and CLI-Interface for the h5-dataformat of the Shepherd-Testbed"
keywords = ["testbed", "beaglebone", "pru", "batteryless", "energyharvesting", "solar"]

authors = [
    {name = "Ingmar Splitt", email = "ingmar.splitt@tu-dresden.de"},
    {name = "Kai Geissdoerfer"}
]
maintainers = [
    {name = "Ingmar Splitt", email = "ingmar.splitt@tu-dresden.de"},
]

readme = {file = "README.md", content-type = "text/markdown"}
license = {file = "LICENSE"}
dynamic = ["version"]

classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "Intended Audience :: Information Technology",
    "Intended Audience :: Science/Research",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Natural Language :: English",
]

requires-python = ">=3.7"
dependencies = [
    "click",
    "h5py",
    "matplotlib",  # full-version
    "numpy",
    "pandas",  # full-version
    "pyYAML",
    "scipy",   # full-version
    "tqdm",    # full-version
]

[project.optional-dependencies]
dev = [
    "black",
    "pylint",
    "flake8",
    "twine",
    "pre-commit",
    "pyright",
    "pandas-stubs",  # for pyright with pandas
]

test = [
    "pytest",
    "pytest-click",
    "coverage",
]

[project.urls]
Documentation = "https://github.com/orgua/shepherd-datalib/blob/main/README.md"
Source = "https://pypi.org/project/shepherd-data/"

[project.scripts]
shepherd-data = "shepherd_data.cli:cli"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
platforms = ["unix", "linux", "osx", "cygwin", "win32", "win64"]
zip-safe = true
#include-package-data = true

[tool.setuptools.packages.find]
where = ["src"]
namespaces = false

[tool.setuptools.dynamic]
version = {attr = "shepherd_data.__version"}

#[tool.setuptools.package-data]
#shepherd_data = [
#    "README.md",
#    "src/examples/*.py",
#    "src/examples/*.iv",
#]

[tool.pytest.ini_options]
addopts = "-vvv" # opts: verbose result for each tests
# TODO: add something like "--cov --cov-report html --cov-report term-missing --cov-fail-under 95"

[tool.coverage.run]
source = ["src"]
