name: Build, install & pytest

on:
  workflow_call:

jobs:
  utest:

    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        python-version: [ "3.13", "3.11", "3.10" ] # 4 versions / years

    runs-on: ${{ matrix.os }}

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-${{ matrix.os }}-${{ matrix.python-version }}
      cancel-in-progress: true

    steps:

      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v5
      - name: Set up Python ${{ matrix.python-version }} ğŸ
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install pip-dependencies ğŸ”§
        run: pip install build
      - name: Install apt-dependencies ğŸ”§
        run: sudo apt install build-essential
        if: ${{ matrix.os == 'ubuntu-latest' }}

      - name: Test-Build core-package ğŸ§±
        run: python -m build
        working-directory: "./shepherd_core"
      - name: Test-Build data-package ğŸ§±
        run: python -m build
        working-directory: "./shepherd_data"

      - name: Install core-package ğŸ§±
        run: pip install .[test,inventory]
        working-directory: "./shepherd_core"
      - name: Install ELF-support ğŸ§±
        run: pip install .[elf]
        working-directory: "./shepherd_core"
        if: ${{ matrix.os != 'windows-latest' }}
      - name: Install data-package ğŸ§±
        run: pip install .[test]
        working-directory: "./shepherd_data"

      - name: Test core-package with pytest ğŸ§«
        run: pytest
        working-directory: "./shepherd_core"
      - name: Test data-package with pytest ğŸ§«
        run: pytest
        working-directory: "./shepherd_data"
