# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: PyTest

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build_package:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [ "3.11", "3.7" ]

    steps:

      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }} ğŸ
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies ğŸ”§
        run: python -m pip install --upgrade pip

      - name: Install core-package ğŸ§±
        run: pip install .[test]
        working-directory: "./shepherd_core"
      - name: Install data-package ğŸ§±
        run: pip install .[test]
        working-directory: "./shepherd_data"

      - name: Test with pytest ğŸ§«
        run: pytest
        working-directory: "./shepherd_data"

  test_package:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v3
      - name: Set up Python ğŸ
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies ğŸ”§
        run: |
          python -m pip install --upgrade pip
          pip install pylint pylint-exit
          pip install build

      - name: Test-Build core-package ğŸ§±
        run: python -m build
        working-directory: "./shepherd_core"
      - name: Test-Build data-package ğŸ§±
        run: python -m build
        working-directory: "./shepherd_data"

      - name: Install Core-Package ğŸ§±
        run: pip install .[test,dev]
        working-directory: "./shepherd_core"
      - name: Install Data-Package ğŸ§±
        run: pip install .[test,dev]
        working-directory: "./shepherd_data"

      - name: Run Pre-Commit Tests ğŸ§ª
        uses: pre-commit/action@v3.0.0

      - name: Test with pytest ğŸ§«
        run: pytest
        working-directory: "./shepherd_data"

      - name: Analyze the code with pylint ğŸ§
        run: pylint $(git ls-files '*.py') || pylint-exit $?
