name: Release tagged Commit

on:
  workflow_call:
  push:
    # branches: [ main ]  # this is handled as OR (push to main OR tagged)
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  run-quality-control:
    uses: ./.github/workflows/quality_assurance.yaml
  release:
    runs-on: ubuntu-latest
    needs:
      - run-quality-control
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v4

      - id: extract-changelog
        uses: sean0x42/markdown-extract@v4
        with:
          file: ./CHANGELOG.md
          pattern: ${{ github.ref_name }}
      - name: Release ğŸƒ
        uses: softprops/action-gh-release@v2
        with:
          body: ${{ steps.extract-changelog.outputs.markdown }}
